"""
Multi-criteria pruning and instance recovery.

Input:
    CCR inference CSV generated by ccr_inference.py

Output:
    reliable_pool.csv
    informative_pool.csv
    anchor_set.csv
    recovered_nodes.csv
    stage_summary.csv
"""

from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity


def get_embedding_columns(df: pd.DataFrame) -> list[str]:
    """Return embedding column names z_0, z_1, ..., z_511."""

    embedding_cols = [
        col for col in df.columns
        if col.startswith("z_")
    ]

    if len(embedding_cols) == 0:
        raise ValueError("No embedding columns found. Expected columns named z_0, z_1, ...")

    return embedding_cols


def reliability_filter(
    df: pd.DataFrame,
    threshold: float = 0.0,
) -> pd.DataFrame:
    """
    Stage 1: reliability-aware filtering.

    Retain beats with CCR-Score >= threshold.
    """

    reliable_df = df[df["ccr_score"] >= threshold].copy()
    return reliable_df


def informativeness_filter(
    reliable_df: pd.DataFrame,
    p_non_threshold: float = 0.5,
) -> pd.DataFrame:
    """
    Stage 2: informativeness enrichment.

    Preferentially retain beats with p_non > threshold.
    """

    informative_df = reliable_df[reliable_df["p_non"] > p_non_threshold].copy()
    return informative_df


def balance_anchor_set(
    informative_df: pd.DataFrame,
    normal_label: int = 0,
    random_state: int = 2024,
) -> pd.DataFrame:
    """
    Stage 3: distributional balancing.

    Retain all non-normal beats.
    Randomly downsample normal beats to match the number of non-normal beats.
    """

    normal_df = informative_df[informative_df["pred_label"] == normal_label].copy()
    non_normal_df = informative_df[informative_df["pred_label"] != normal_label].copy()

    if len(non_normal_df) == 0:
        return normal_df.copy()

    if len(normal_df) == 0:
        return non_normal_df.copy()

    n_normal_keep = min(len(normal_df), len(non_normal_df))

    sampled_normal_df = normal_df.sample(
        n=n_normal_keep,
        random_state=random_state,
        replace=False,
    )

    anchor_df = pd.concat(
        [non_normal_df, sampled_normal_df],
        axis=0,
    )

    anchor_df = anchor_df.sort_values("beat_index").reset_index(drop=True)

    return anchor_df


def recover_instances(
    anchor_df: pd.DataFrame,
    reliable_df: pd.DataFrame,
    similarity_threshold: float = 0.8,
) -> pd.DataFrame:
    """
    Stage 4: instance recovery.

    Recover reliable beats whose cosine similarity to at least one anchor beat
    is greater than similarity_threshold.
    """

    if len(anchor_df) == 0:
        return anchor_df.copy()

    embedding_cols = get_embedding_columns(reliable_df)

    anchor_embeddings = anchor_df[embedding_cols].to_numpy(dtype=np.float32)
    reliable_embeddings = reliable_df[embedding_cols].to_numpy(dtype=np.float32)

    similarity_matrix = cosine_similarity(
        anchor_embeddings,
        reliable_embeddings,
    )

    recover_mask = (similarity_matrix > similarity_threshold).any(axis=0)

    recovered_df = reliable_df[recover_mask].copy()

    # Always keep anchor beats even if numerical precision causes mismatch.
    recovered_df = pd.concat(
        [recovered_df, anchor_df],
        axis=0,
    )

    recovered_df = (
        recovered_df
        .drop_duplicates(subset=["patient_id", "beat_id"])
        .sort_values("beat_index")
        .reset_index(drop=True)
    )

    return recovered_df


def summarize_stages(
    full_df: pd.DataFrame,
    reliable_df: pd.DataFrame,
    informative_df: pd.DataFrame,
    anchor_df: pd.DataFrame,
    recovered_df: pd.DataFrame,
) -> pd.DataFrame:
    """Create stage-wise node count summary."""

    rows = []

    stages = [
        ("all_beats", full_df),
        ("reliable_pool", reliable_df),
        ("informative_pool", informative_df),
        ("anchor_set", anchor_df),
        ("recovered_nodes", recovered_df),
    ]

    total = len(full_df)

    for stage_name, stage_df in stages:

        n_total = len(stage_df)
        n_normal = int((stage_df["pred_label"] == 0).sum()) if n_total > 0 else 0
        n_non_normal = int((stage_df["pred_label"] != 0).sum()) if n_total > 0 else 0

        rows.append({
            "stage": stage_name,
            "n_beats": n_total,
            "retention_ratio": n_total / total if total > 0 else np.nan,
            "n_normal": n_normal,
            "n_non_normal": n_non_normal,
            "non_normal_ratio": n_non_normal / n_total if n_total > 0 else np.nan,
        })

    return pd.DataFrame(rows)


def run_pruning_recovery(
    input_csv: str,
    output_dir: str,
    reliability_threshold: float = 0.0,
    p_non_threshold: float = 0.5,
    similarity_threshold: float = 0.8,
    normal_label: int = 0,
    random_state: int = 42,
):
    """
    Run the complete multi-criteria pruning and recovery pipeline.
    """

    input_csv = Path(input_csv)
    output_dir = Path(output_dir)

    output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    df = pd.read_csv(input_csv)

    required_columns = {
        "patient_id",
        "beat_id",
        "beat_index",
        "pred_label",
        "p_non",
        "ccr_score",
    }

    missing_columns = required_columns - set(df.columns)

    if missing_columns:
        raise ValueError(f"Missing required columns: {missing_columns}")

    reliable_df = reliability_filter(
        df,
        threshold=reliability_threshold,
    )

    informative_df = informativeness_filter(
        reliable_df,
        p_non_threshold=p_non_threshold,
    )

    anchor_df = balance_anchor_set(
        informative_df,
        normal_label=normal_label,
        random_state=random_state,
    )

    recovered_df = recover_instances(
        anchor_df=anchor_df,
        reliable_df=reliable_df,
        similarity_threshold=similarity_threshold,
    )

    summary_df = summarize_stages(
        full_df=df,
        reliable_df=reliable_df,
        informative_df=informative_df,
        anchor_df=anchor_df,
        recovered_df=recovered_df,
    )

    reliable_df.to_csv(output_dir / "reliable_pool.csv", index=False)
    informative_df.to_csv(output_dir / "informative_pool.csv", index=False)
    anchor_df.to_csv(output_dir / "anchor_set.csv", index=False)
    recovered_df.to_csv(output_dir / "recovered_nodes.csv", index=False)
    summary_df.to_csv(output_dir / "stage_summary.csv", index=False)

    print(f"Saved pruning/recovery outputs to: {output_dir}")
    print(summary_df)

    return {
        "reliable_pool": reliable_df,
        "informative_pool": informative_df,
        "anchor_set": anchor_df,
        "recovered_nodes": recovered_df,
        "stage_summary": summary_df,
    }


if __name__ == "__main__":

    input_dir = Path("results/pruning_recovery")
    output_root = Path("results/pruning_recovery_nodes")

    csv_files = sorted(input_dir.glob("patient_*.csv"))

    print(f"Found {len(csv_files)} CCR inference files.")

    for csv_path in csv_files:

        patient_id = csv_path.stem

        print("\n" + "=" * 60)
        print(f"Running pruning and recovery for: {patient_id}")

        run_pruning_recovery(
            input_csv=str(csv_path),
            output_dir=str(output_root / patient_id),
            reliability_threshold=0.0,
            p_non_threshold=0.5,
            similarity_threshold=0.8,
            normal_label=0,
            random_state=42,
        )

    print("\nAll pruning/recovery tests passed.")